apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutlery
spec:
  selector:
    matchLabels:
      app: cutlery
  replicas: 1
  template:
    metadata:
      labels:
        app: cutlery
    spec:
      containers:
      - name: cutlery
        image: cutlery:v001
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"            
          limits:
            memory: "64Mi"
            cpu: 100m
        ports:
        - containerPort: 8080
